---
title: Nick Lagattuta - Cloud Engineer
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: nick@lagattuta.com
description: Nick Lagattuta is a cloud engineer and is an AWS certified Solutions
  Architect Associate and Sysops Administrator Associate.
baseurl: 
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
